let text = `
[
  {"type":"directory","name":"/builds/thesarthakbhardwaj/regressiontest/test","contents":[
    {"type":"directory","name":"CMap2","contents":[
      {"type":"directory","name":"12","contents":[
        {"type":"directory","name":"3","contents":[
        ]},
        {"type":"directory","name":"4","contents":[
        ]}
      ]},
      {"type":"directory","name":"20","contents":[
        {"type":"directory","name":"4","contents":[
        ]}
      ]}
    ]},
    {"type":"directory","name":"Composite","contents":[
    ]},
    {"type":"directory","name":"Distortable","contents":[
      {"type":"directory","name":"12","contents":[
        {"type":"directory","name":"3","contents":[
        ]},
        {"type":"directory","name":"4","contents":[
        ]},
        {"type":"directory","name":"5","contents":[
        ]}
      ]},
      {"type":"directory","name":"20","contents":[
        {"type":"directory","name":"3","contents":[
        ]},
        {"type":"directory","name":"4","contents":[
        ]},
        {"type":"directory","name":"5","contents":[
        ]}
      ]}
    ]},
    {"type":"directory","name":"UVSTest","contents":[
      {"type":"directory","name":"12","contents":[
        {"type":"directory","name":"3","contents":[
        ]},
        {"type":"directory","name":"4","contents":[
        ]}
      ]},
      {"type":"directory","name":"20","contents":[
        {"type":"directory","name":"3","contents":[
        ]},
        {"type":"directory","name":"4","contents":[
        ]}
      ]}
    ]}
  ]},
  {"type":"report","directories":23}
]`;
